### ISSUE TITLE
Question: any reference for AR Quick Look limitations?

### ISSUE THREAD

**Issue by darknoon** [google/usd_from_gltf#2]
As someone working on USDZ support directly in blender this list is very illuminating:
https://github.com/google/usd_from_gltf#emulated-functionality-for-ar-quick-look

How did you discover the list of limitations here on AR Quick Look compared to Preview Surface? I have wondered about how much of this functionality would be non-existent. Was it all by trial and error?

**Comment by C0DED00D** [comment]
Thanks for your interest! It was all by trial and error.
