### ISSUE TITLE
Handling of baseColorFactor alpha highlights Quick Look renderer issue

### ISSUE THREAD

**Issue by TyLindberg** [google/usd_from_gltf#28]
Currently when a glTF file specifies a `baseColorFactor` with an alpha value less than 1 and sets `alphaMode` to `BLEND`, the converter will bake that alpha value into base color texture. Doing so causes the transparency [rendering issue referenced in the README](https://github.com/google/usd_from_gltf#rendering-differences-between-gltf-and-ar-quick-look) to occur. If instead the the alpha value is set directly in the USD material and the texture is left unchanged, the renderer better represents the transparency while also decreasing overall file size by keeping JPEG compression on the texture.

I've attached a source glb file with an example alpha material along with two directories of USD assets. One is the output from `usd_from_gltf` and the other is model with the alpha set directly in the USD material.

[usd_from_gltf_alpha_example.zip](https://github.com/google/usd_from_gltf/files/3821892/usd_from_gltf_alpha_example.zip)

**Comment by C0DED00D** [comment]
Hmmm... I thought there was an issue with material colors which is why we
did that way. However, we did most of the compatibility testing on iOS 12.
What version of iOS are you using for testing? Did you try on both? We've
noticed difference in the feature set but have largely been trying to keep
compatibility with iOS 12 for now.

Thanks!

**Comment by TyLindberg** [comment]
Yeah, I'm seeing the same rendering results on iOS 12 and 13.

**Comment by C0DED00D** [comment]
Ok, we'll add it to our backlog to investigate!

**Comment by hujasonx** [comment]
@TyLindberg Hi Tyler, can you try again with the latest code? I believe this should be fixed now.

**Comment by TyLindberg** [comment]
Just ran a quick test and it seems to be working on my end. Thanks for the fix!
