### ISSUE TITLE
ERROR: COMMAND failed: cmake --build ....

### ISSUE THREAD

**Issue by r23** [google/usd_from_gltf#29]
Hello

Thanks for the great program. I'm trying to install usd_from_gltf on a Windows 10 machine. 

`python C:\UFG_SRC\tools\ufginstall\ufginstall.py C:\Programm\UFG2 C:\Programm\USD --testdata`

> 
cmake C:\UFG_SRC -DCMAKE_INSTALL_PREFIX=C:\Programm\UFG2 -DCMAKE_PREFIX_PATH=C:\Programm\UFG2 -DUSD_DIR=C:\Programm\USD -DCMAKE_GENERATOR_PLATFORM=x64
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.23.28106.4
-- The CXX compiler identification is MSVC 19.23.28106.4
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/libs/python37.lib (found version "3.7") found components: Development 
-- Found ZLIB: C:/Program Files/zlib/lib/zlib.lib (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Programm/UFG2/build/UFG_SRC

I'm getting the following error and I would appreciate any help!

ERROR: COMMAND failed: cmake --build ....

![grafik](https://user-images.githubusercontent.com/396063/68521691-d2560900-02a3-11ea-9621-d116f6cf9c7a.png)

The Error.log 

cmake --build . --config Release --target install -- /m
Microsoft (R)-Build-Engine, Version 16.3.2+e481bbf88 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Checking Build System
  Building Custom Rule C:/UFG_SRC/gltf/CMakeLists.txt
  internal_util.cc
  load.cc
  memory_stream.cc
  message.cc
  stream.cc
  validate.cc
  cache.cc
  disk_stream.cc
  disk_util.cc
  glb_stream.cc
  gltf.cc
  image_parsing.cc
  Code wird generiert...
  gltf.vcxproj -> C:\Programm\UFG2\build\UFG_SRC\gltf\Release\gltf.lib
  Building Custom Rule C:/UFG_SRC/common/CMakeLists.txt
  config.cc
  Unknown compiler version - please run the configure tests and report the results
  logging.cc
  Unknown compiler version - please run the configure tests and report the results
  platform.cc
  Code wird generiert...
  common.vcxproj -> C:\Programm\UFG2\build\UFG_SRC\common\Release\common.lib
  Building Custom Rule C:/UFG_SRC/process/CMakeLists.txt
  math.cc
  Unknown compiler version - please run the configure tests and report the results
  mesh.cc
  Unknown compiler version - please run the configure tests and report the results
  process_util.cc
  Unknown compiler version - please run the configure tests and report the results
  skin.cc
  Unknown compiler version - please run the configure tests and report the results
  animation.cc
  Unknown compiler version - please run the configure tests and report the results
  color.cc
  Unknown compiler version - please run the configure tests and report the results
  float_image.cc
  Unknown compiler version - please run the configure tests and report the results
  image.cc
  Unknown compiler version - please run the configure tests and report the results
  image_fallback.cc
  Unknown compiler version - please run the configure tests and report the results
  image_gif.cc
  Unknown compiler version - please run the configure tests and report the results
  image_jpg.cc
  Unknown compiler version - please run the configure tests and report the results
  image_png.cc
  Unknown compiler version - please run the configure tests and report the results
  Code wird generiert...
  process.vcxproj -> C:\Programm\UFG2\build\UFG_SRC\process\Release\process.lib
  Building Custom Rule C:/UFG_SRC/convert/CMakeLists.txt
  tokens.cc
  Unknown compiler version - please run the configure tests and report the results
  convert_util.cc
  Unknown compiler version - please run the configure tests and report the results
  converter.cc
  Unknown compiler version - please run the configure tests and report the results
C:\Programm\USD\include\pxr/usd/usd/modelAPI.h(324,1): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "BOOST_VMD_IS_TUPLE". [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/usd/usd/modelAPI.h(324,1): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "BOOST_VMD_DETAIL_IS_TUPLE". [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/usd/usd/modelAPI.h(324,1): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "BOOST_VMD_DETAIL_PARENS_SPLIT". [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/usd/usd/modelAPI.h(324,1): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "BOOST_PP_SEQ_DETAIL_IS_NOT_EMPTY". [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/usd/usd/modelAPI.h(324,1): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "BOOST_PP_SEQ_DETAIL_EMPTY_SIZE". [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/usd/usd/modelAPI.h(324,1): warning C4003: Nicht genügend Argumente für den Aufruf des funktionsähnlichen Makros "BOOST_PP_TUPLE_SIZE". [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(443,43): error C2440: "Initialisierung": "initializer list" kann nicht in "pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>" konvertiert werden [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(450,3): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(451,42): error C2440: "Initialisierung": "initializer list" kann nicht in "pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>" konvertiert werden [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(458,3): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(460,43): error C2440: "Initialisierung": "initializer list" kann nicht in "pxrInternal_v0_18__pxrReserved__::VtArray<int>" konvertiert werden [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(467,3): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(501,66): error C2664: "pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>::VtArray(const pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f> &)" : Konvertierung von Argument 1 von "initializer list" in "size_t" nicht möglich [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(501,33): message : Der Initialisierer enthält zu viele Elemente. [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/base/vt/array.h(300,5): message : Siehe Deklaration von "pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>::VtArray" [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(727,66): error C2664: "pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>::VtArray(const pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f> &)" : Konvertierung von Argument 1 von "initializer list" in "size_t" nicht möglich [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\UFG_SRC\convert\converter.cc(727,35): message : Der Initialisierer enthält zu viele Elemente. [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
  materializer.cc
  package.cc
  texturator.cc
  Code wird generiert...
C:\Programm\USD\include\pxr/base/vt/array.h(300,5): message : Siehe Deklaration von "pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>::VtArray" [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/base/vt/array.h(300,5): message : Unknown compiler version - please run the configure tests and report the results [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/base/vt/array.h(300,5): message : Unknown compiler version - please run the configure tests and report the results [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]
C:\Programm\USD\include\pxr/base/vt/array.h(300,5): message : Unknown compiler version - please run the configure tests and report the results [C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj]

The error log is unfortunately partly in German. 

thanks
Ralf

**Comment by r23** [comment]
error C2440: 'initializing' : cannot convert from 'initializer-list'
'pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>" konvertiert werden 	C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj	C:\UFG_SRC\convert\converter.cc	443	

error C2440: 'initializing' : cannot convert from 'initializer-List' ist'"pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>" konvertiert werden 	C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj	C:\UFG_SRC\convert\converter.cc	451	


error C2440: 'initializing' : cannot convert from 'initializer-list "pxrInternal_v0_18__pxrReserved__::VtArray<int>" konvertiert werden 	C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj	C:\UFG_SRC\convert\converter.cc	460		


error	C2664	"pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>::VtArray(const pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f> &)" : Konvertierung von Argument 1 von "initializer list" in "size_t" nicht möglich 	C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj	C:\UFG_SRC\convert\converter.cc	501		


Fehler	C2664	"pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f>::VtArray(const pxrInternal_v0_18__pxrReserved__::VtArray<pxrInternal_v0_18__pxrReserved__::GfVec3f> &)" : Konvertierung von Argument 1 von "initializer list" in "size_t" nicht möglich 	C:\Programm\UFG2\build\UFG_SRC\convert\convert.vcxproj	C:\UFG_SRC\convert\converter.cc	727		

![grafik](https://user-images.githubusercontent.com/396063/68522645-c2dbbd80-02ad-11ea-92a7-6aa1d2918a08.png)

**Comment by C0DED00D** [comment]
What version of libusd are you using? It looks like there might be a newer
version that isn't compiling. I don't have my source code handy right now,
but I believe we have only tested with 19.07 or something like that. Can
you try an older build of USD to see if that works?

**Comment by r23** [comment]
Thank you very much! I have installed the current USD version and it works!

![grafik](https://user-images.githubusercontent.com/396063/68530839-7a9fb800-030c-11ea-87a1-1692f1336973.png)
