### ISSUE TITLE
Multiple Animated Objects GLTF does not convert to USDZ properly

### ISSUE THREAD

**Issue by enzyme69** [google/usd_from_gltf#3]
I have this really weird issue where I simply have a bunch of animated objects (no armature) but it never translate properly into USDZ. Only 1 object animated.

But if I use gltf viewer, all objects are animating.

I have tried using Apple usdzconvert, gltf2usd ... none of them are working. Including this one from google. But perhaps you can take look?

[simpler_still_does_not_work.zip](https://github.com/google/usd_from_gltf/files/3452011/simpler_still_does_not_work.zip)

[ManyAnim.zip](https://github.com/google/usd_from_gltf/files/3452017/ManyAnim.zip)

**Comment by enzyme69** [comment]
Ok the current solution seems to be to try to "collapse" all animation into a single action. Exporting to Collada DAE in Blender 3D and importing back seems to be one solution. Or try exporting to Sketchfab and download as GLTF.

**Comment by C0DED00D** [comment]
Hello! I looked at both in [Don McCurdy's glTF viewer](https://gltf-viewer.donmccurdy.com/), which is a good reference, and in both files, only one ring is moving. Could there be an issue with the original glTF exporting process where the animation isn't encoded in a standard way? Maybe that's what the more complicated exporting process fixes. 

Thanks!

**Comment by C0DED00D** [comment]
I'm closing this issue. Feel free to reopen if you run into problems where it works in glTF viewers and not in our converter.

**Comment by saurabhburadkar** [comment]
I am trying to export this model in usdz but its not properly exporting this mode
[RobotExpressive.glb.zip](https://github.com/google/usd_from_gltf/files/9147993/RobotExpressive.glb.zip)
l

**Comment by saurabhburadkar** [comment]
this model have multiple animations
