### ISSUE TITLE
UFG_ERROR_LOAD_PLUGINS when using usd_from_gltf command line tool

### ISSUE THREAD

**Issue by arzezniczak** [google/usd_from_gltf#31]
Hello,
I've build UFG, as a result I've got usd_from_gltf.exe in bin folder. When I tried to run it first it was complaining about missing DLLs but I've copied (a lot) them from USD install bin and lib directory and it's now at least starting.
But I cannot go any further because it's now giving me: 
`ERROR: Unable to load USD plugins. Could not locate plugin search path. [UFG_ERROR_LOAD_PLUGINS]`
I've tried to set `--plugin_path` to {UFG_install}\bin\ufg_plugin directory and {USD_install}\plugin\usd but it's telling me only that:
`ERROR: Unable to load USD plugins. No plugins found at search path: ... [UFG_ERROR_LOAD_PLUGINS]`

In code I see that it's using `GetPluginWithName("usd")`. Where do I get this plugin? What plugin does it expect?

I'm using Windows 10 and VS2017.

**Comment by C0DED00D** [comment]
When I install it, I leave libUSD where it is and just make sure the libraries can load from there by putting it on my path. Can you go back to a clean install of libUSD and see if you can get the dll errors resolved by adjusting your path?

Thanks!

**Comment by arzezniczak** [comment]
You are right! I've builded USD again and set up env paths correctly and now usd_from_gltf.exe works without any additional work.
I think previously somehow I had omitted message from USD installer to set up paths after installation.
