### ISSUE TITLE
Option for skipping Python linking in build

### ISSUE THREAD

**Issue by TyLindberg** [google/usd_from_gltf#33]
I noticed that commit 2a5f9409e0500c4d651633af2c7a48c5ee077990 seems to have rolled back the changes in #26. I assume this was because it broke builds on one of the platforms.

In order to still include the ability to not link against the Python libraries, I'm thinking that adding a build arg, something like `--no-python`, would be a good solution. This would allow usd_from_gltf to still be run in environments that don't have access to Python libraries.

Let me know your thoughts.

**Comment by C0DED00D** [comment]
This was unintentional. I suspect there was an issue pulling in this change to our internal repository. We'll put that on our backlog. Good catch!

**Comment by TyLindberg** [comment]
Awesome, thanks!

**Comment by michaelvbe** [comment]
Would you recommend rolling back to an earlier commit (before https://github.com/google/usd_from_gltf/commit/2a5f9409e0500c4d651633af2c7a48c5ee077990), or building USD with python?

**Comment by C0DED00D** [comment]
I would build with Python until we can investigate the issue. Sorry for the trouble!

**Comment by hujasonx** [comment]
Looks like we missed a step with approving your PR @TyLindberg, [this commit](https://github.com/google/usd_from_gltf/commit/2387ab7f6678ef74cf2aaebf1d29da106020d9eb) should re-implement your changes. Thanks for your patience!

**Comment by TyLindberg** [comment]
Thanks @hujasonx!
