### ISSUE TITLE
--noprefer_jpeg function in usdconvert doesn't work

### ISSUE THREAD

**Issue by Cold5tar** [google/usd_from_gltf#36]
### Problem:
It seems that at the moment usdconvert is forcing all of the `.png` files to `.jpg` files. This is causing major issues for some files.  

### Details:
As I can see,  `--prefer_jpeg` is set to default, but setting `--noprefer_jpeg` during a conversion doesn't do anything. I've tested my syntax with other commands and they worked.

### To reproduce:
**Use converter command: `usd_from_gltf.exe --noprefer_jpeg "input.gltf" "output.usdz"`**
    

***edit**: Seems that if `.png` has transparency mask, converter doesn't force it to `.jpg`

**Comment by C0DED00D** [comment]
Thanks for letting us know. We will investigate.

**Comment by hujasonx** [comment]
Hi @Cold5tar, let us know if [this commit](https://github.com/google/usd_from_gltf/commit/3bf441e0eb5b6cfbe487bbf1e2b42b7447c43d02) fixes your issue! Thanks for your patience.

**Comment by Cold5tar** [comment]
Thank you, issue was resolved!
