### ISSUE TITLE
Failure to convert Blender glTF files to USDZ using usd_from_gltf

### ISSUE THREAD

**Issue by shyam98** [google/usd_from_gltf#46]
Hello, I am having an issue with glTF files that I created using Blender. When I try to run the converter, I am greeted with the following error: 
ERROR: Cannot open file for read: /home/ec2-user/docker-gltf-to-udsz/gltf/Shoe.gltf [GLTF_ERROR_IO_OPEN_READ]

I've tried this with many different glTF files from blender with the same issue. Please let me know if there is something I can do to fix this.

**Comment by victor-gabou** [comment]
Hello @shyam98,

Do you remember what was your problem about? I'm having the same issue

Thanks

**Comment by TheCanadians** [comment]
I am having the same issue. Did anybody solve this?

**Comment by Nnadozie** [comment]
@TheCanadians, @victor-gabou I had this same issue just now.

_**Enviroment**_
DockerHub installed on Windows 10, and using [this docker image](https://github.com/leon/docker-gltf-to-udsz)

_**Recreate Error**_
running the command:

```
docker run -it --rm -v $(PWD):/usr/app leon/usd-from-gltf:latest one.glb done.usdz
```
Gives the error:

```
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

and then running:

```
winpty docker run -it --rm -v $(PWD):/usr/app leon/usd-from-gltf:latest one.glb done.usdz
```

gives:

```
ERROR: Cannot open file for read: one.glb [GLTF_ERROR_IO_OPEN_READ]
failed to resize tty, using default size
```

_**current fix**_

Switching over to cmd and using absolute paths works fine

```
docker run -it --rm -v C:\Users\neoke\Downloads\app:/usr/app leon/usd-from-gltf:latest one.glb done.usdz
```

I get my converted file in my mounted app folder.

_**hunch**_
I imagine that if you aren't using docker, it might still have something to do with absolute paths.
