### ISSUE TITLE
Error while installing usd_from_gltf : No rule to make target '$USDROOT/lib/libboost_python.so', needed by 'usd_from_gltf/usd_from_gltf'

### ISSUE THREAD

**Issue by AksAman** [google/usd_from_gltf#60]
* {USD} = USDROOT
* {UFG_SRC} = usd_from_gltf
* {UFG_BUILD} = UFG_BUILD
 

`python usd_from_gltf/tools/ufginstall/ufginstall.py UFG_BUILD USDROOT
Install Settings:
  Source Directory:   /home/aman/usd_from_gltf
  Install Directory:  /home/aman/UFG_BUILD
  USD Directory:      /home/aman/USDROOT
  Download Directory: /home/aman/UFG_BUILD/src
  Build Directory:    /home/aman/UFG_BUILD/build
  Build Config:       Release
  CMake Generator:    Default
  Already Installed:  DRACO, GIF, JPG, JSON, ZLIB, PNG, STB_IMAGE, TCLAP
  Installing:         USD_FROM_GLTF

-------- Installing USD_FROM_GLTF --------
  USD_FROM_GLTF: CWD: /home/aman/UFG_BUILD/build/usd_from_gltf
  USD_FROM_GLTF: Run: cmake /home/aman/usd_from_gltf -DCMAKE_INSTALL_PREFIX=/home/aman/UFG_BUILD -DCMAKE_PREFIX_PATH=/home/aman/UFG_BUILD -DUSD_DIR=/home/aman/USDROOT
  USD_FROM_GLTF: CWD: /home/aman/UFG_BUILD/build/usd_from_gltf
  USD_FROM_GLTF: Run: cmake --build . --config Release --target install --
[ 30%] Built target gltf
[ 40%] Built target common
[ 71%] Built target process
[ 88%] Built target convert
make[2]: *** No rule to make target '/home/aman/USDROOT/lib/libboost_python.so', needed by 'usd_from_gltf/usd_from_gltf'.  Stop.
CMakeFiles/Makefile2:331: recipe for target 'usd_from_gltf/CMakeFiles/usd_from_gltf.dir/all' failed
make[1]: *** [usd_from_gltf/CMakeFiles/usd_from_gltf.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Schlomoh** [comment]
ive had the same problem but found the solution to be quite simple. In the newer USD install it may not find the file 'libboost_python.so' because it is actually called 'libboost_python38.so'. Just look up the file in your USD install directory, duplicate it and take away the '38'. The try the installation again. 
At least that was the solution to my installation failing. hope that helps

**Comment by AksAman** [comment]
> ive had the same problem but found the solution to be quite simple. In the newer USD install it may not find the file 'libboost_python.so' because it is actually called 'libboost_python38.so'. Just look up the file in your USD install directory, duplicate it and take away the '38'. The try the installation again.
> At least that was the solution to my installation failing. hope that helps

Thanks Schlomoh! What i did instead was i renamed the line https://github.com/google/usd_from_gltf/blob/2387ab7f6678ef74cf2aaebf1d29da106020d9eb/CMakeLists.txt#L87
to
`list(APPEND USD_LIBS "${USD_DIR}/lib/libboost_python36.so")` and it worked!
